#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false
#springdoc.packages-to-scan=com.Kata.spring.swagger.controller
springdoc.swagger-ui.path=/Kata-documentation
springdoc.api-docs.path=/Kata-api-docs
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

Kata.openapi.dev-url=http://localhost:8080
Kata.openapi.prod-url=https://Kata-api.com