#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false
#springdoc.packages-to-scan=com.Kata.spring.swagger.controller
springdoc.swagger-ui.path=/Kata-documentation
springdoc.api-docs.path=/Kata-api-docs
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

Kata.openapi.dev-url=http://localhost:8080
Kata.openapi.prod-url=https://Kata-api.com

kata.openapi.source-file=inputs/input.txt
kata.openapi.dest-file=dest/output.txt

spring.datasource.url=jdbc:h2:mem:batchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2

# Init automatique des tables batch
spring.batch.jdbc.initialize-schema=always

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.schema-locations=classpath:org/springframework/batch/core/schema-h2.sql
